title: Hey, I'm Fran Martín
author: Fran Martín Rivas
color: "#2B546B"
twitter: __franmartin
description: Hey, glad you are here! My name is Fran and I am a enviromental scientist converted into GIS analyst and geospatial developer.
sass:
    sass_dir: assets/_sass
    style: compressed


plugins:
  - jekyll-redirect-from
